package com.greenvenom.validation.domain

enum class ValidationError {
    EMPTY_USER_NAME,
    EMPTY_EMAIL,
    EMPTY_PASSWORD,
    EMPTY_PASSWORD_CONFIRMATION,
    PASSWORDS_MISMATCH,
    INVALID_EMAIL,
    INVALID_OTP,
    MINIMUM_6_CHARACTERS,
    MINIMUM_8_CHARACTERS,
    MINIMUM_1_NUMBER,
    MINIMUM_1_LOWERCASE_LETTER,
    MINIMUM_1_UPPERCASE_LETTER,
    MINIMUM_1_SPECIAL_CHARACTER,
    EMPTY_NAME,
    INVALID_CHARACTERS,
    INSUFFICIENT_PARTS,
    INVALID_PHONE_NUMBER
}